apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: pod-k8s-secret-4grbz-disable-secret-access
  namespace: default
spec:
  selector:
    matchLabels:
      app: k8s-secret-example
  file:
    matchDirectories:
    - dir: /etc/secret/
      recursive: true
      fromSource:
      - path: /bin/ls
      - path: /bin/mknod
      - path: /bin/chgrp
      - path: /bin/lsblk
      - path: /bin/zfgrep
      - path: /bin/tar
      - path: /bin/zcmp
      - path: /bin/mv
      - path: /bin/sleep
      - path: /bin/egrep
      - path: /bin/hostname
      - path: /bin/cat
  action:
    Block
