apiVersion: v1
kind: Pod
metadata:
  name: mypod
spec:
  containers:
  - name: mypod
    image: nginx
    envFrom:
      - secretRef:
          name: mysecret
  #   volumeMounts:
  #   - name: foo
  #     mountPath: "/etc/foo"
  #     readOnly: true
  # volumes:
  # - name: foo
  #   secret:
  #     secretName: mysecret
  #     optional: false # default setting; "mysecret" must exist

