apiVersion: security.kubearmor.com/v1
kind: KubeArmorPolicy
metadata:
  name: weather-service-disable-secret-access
  namespace: default
spec:
  selector:
    matchLabels:
      app: k8s-secret-example
  # process:
  #   matchDirectories:
  #   - dir: /sbin/
  #     recursive: true
  file:
    matchDirectories:
    - dir: /etc/secret/
      recursive: true
      fromSource:
      - path: /bin/ls
      - path: /bin/cat
      - path: 
  action:
    Block
